### ISSUE TITLE
算法宏包的加载是否有错？

### ISSUE THREAD

**Issue by Kakin-Wu** [DeeDive/BJFUThesis#6]
bjfusetup.tex 文件 line 38，应该加载的或许是 “algorithms” 而不是 “algorithm”？因为我是 TinyTeX 用户，在安装缺少的宏包时发现 CTAN 上似乎没有叫作 “algorithm” 的宏包。谢谢你们的贡献！这个项目对我太有帮助了！

**Comment by DeeDive** [comment]
algorithms 和 algorithm + algorithmic 应该都是可以的，见这里的第一句话https://www.ctan.org/pkg/algorithms

```
Consists of two environments: algorithm and algorithmic. 
```

**Comment by Kakin-Wu** [comment]
懂了，谢谢。
