### ISSUE TITLE
没有发现摘要页中的毕设名、指导老师、学生名、班级等相关信息

### ISSUE THREAD

**Issue by ZhizhuoUp** [DeeDive/BJFUThesis#7]
看毕设规范中规定了，要在中英文摘要中加入上述的信息，可是没有在这个模板中发现相关的代码，是作者没有将其加入模板中，还是在我没注意到的地方注释掉了呢？

**Comment by DeeDive** [comment]
嗯嗯感谢你的提问！当前的版本设计没有在摘要页加入这些内容，是根据这个来的：[撰写时依据的规范](https://github.com/DeeDive/BJFUThesis/blob/main/docs/%EF%BC%882021%E5%B9%B4%E7%89%88%EF%BC%89%E5%8C%97%E4%BA%AC%E6%9E%97%E4%B8%9A%E5%A4%A7%E5%AD%A6%E6%9C%AC%E7%A7%91%E6%AF%95%E4%B8%9A%E8%AE%BA%E6%96%87%EF%BC%88%E8%AE%BE%E8%AE%A1%EF%BC%89%E6%92%B0%E5%86%99%E4%B8%8E%E5%8D%B0%E5%88%B6%E8%A7%84%E8%8C%83.pdf)，如果新规范中有要求欢迎添加补充！

**Comment by ZhizhuoUp** [comment]
> 

发现是我电脑里的版本太久了没有注意到更新，辛苦作者提醒了！
